2023-11-24 06:23:03,349 - root - INFO - Initiating present weather
2023-11-24 06:23:03,353 - asyncio - DEBUG - Using selector: EpollSelector
2023-11-24 06:23:06,640 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): radar.bmkg.go.id:8060
2023-11-24 06:23:09,707 - root - INFO - Initiating present weather
2023-11-24 06:23:09,709 - asyncio - DEBUG - Using selector: EpollSelector
2023-11-24 06:23:13,216 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): radar.bmkg.go.id:8060
2023-11-24 06:23:13,284 - urllib3.connectionpool - DEBUG - https://radar.bmkg.go.id:8060 "GET /getRadarGeotif?token=19387e71e78522ae4172ec0fda640983b8438c9cfa0ca571623cb69d8327&radar=amandemenForecast&type=latest HTTP/1.1" 200 90
2023-11-24 06:23:13,287 - rasterio.env - DEBUG - Entering env context: <rasterio.env.Env object at 0x7f5420e8c1a0>
2023-11-24 06:23:13,288 - rasterio.env - DEBUG - Starting outermost env
2023-11-24 06:23:13,288 - rasterio.env - DEBUG - No GDAL environment exists
2023-11-24 06:23:13,288 - rasterio.env - DEBUG - New GDAL environment <rasterio._env.GDALEnv object at 0x7f54206153c0> created
2023-11-24 06:23:13,293 - rasterio._filepath - DEBUG - Installing FilePath filesystem handler plugin...
2023-11-24 06:23:13,293 - rasterio._env - DEBUG - GDAL data found in package: path='/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/rasterio/gdal_data'.
2023-11-24 06:23:13,293 - rasterio._env - DEBUG - PROJ_LIB found in environment.
2023-11-24 06:23:13,293 - rasterio._env - DEBUG - Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x7f54206153c0>.
2023-11-24 06:23:13,294 - rasterio.env - DEBUG - Entered env context: <rasterio.env.Env object at 0x7f5420e8c1a0>
2023-11-24 06:23:13,294 - rasterio._base - DEBUG - Sharing flag: 0
2023-11-24 06:23:13,495 - rasterio._base - DEBUG - Nodata success: 1, Nodata value: nan
2023-11-24 06:23:13,496 - rasterio._base - DEBUG - Dataset <open DatasetReader name='https://radar.bmkg.go.id/raster/radarsatelit_202311240620.tif' mode='r'> is started.
2023-11-24 06:23:13,496 - rasterio.env - DEBUG - Exiting env context: <rasterio.env.Env object at 0x7f5420e8c1a0>
2023-11-24 06:23:13,496 - rasterio.env - DEBUG - Cleared existing <rasterio._env.GDALEnv object at 0x7f54206153c0> options
2023-11-24 06:23:13,497 - rasterio._env - DEBUG - Stopped GDALEnv <rasterio._env.GDALEnv object at 0x7f54206153c0>.
2023-11-24 06:23:13,497 - rasterio.env - DEBUG - Exiting outermost env
2023-11-24 06:23:13,497 - rasterio.env - DEBUG - Exited env context: <rasterio.env.Env object at 0x7f5420e8c1a0>
2023-11-24 06:23:13,497 - rasterio.env - DEBUG - Entering env context: <rasterio.env.Env object at 0x7f5420e8c0b0>
2023-11-24 06:23:13,497 - rasterio.env - DEBUG - Starting outermost env
2023-11-24 06:23:13,497 - rasterio.env - DEBUG - No GDAL environment exists
2023-11-24 06:23:13,497 - rasterio.env - DEBUG - New GDAL environment <rasterio._env.GDALEnv object at 0x7f54206153c0> created
2023-11-24 06:23:13,498 - rasterio._env - DEBUG - GDAL data found in package: path='/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/rasterio/gdal_data'.
2023-11-24 06:23:13,498 - rasterio._env - DEBUG - PROJ_LIB found in environment.
2023-11-24 06:23:13,498 - rasterio._env - DEBUG - Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x7f54206153c0>.
2023-11-24 06:23:13,498 - rasterio.env - DEBUG - Entered env context: <rasterio.env.Env object at 0x7f5420e8c0b0>
2023-11-24 06:23:13,499 - rasterio.env - DEBUG - Got a copy of environment <rasterio._env.GDALEnv object at 0x7f54206153c0> options
2023-11-24 06:23:13,499 - rasterio.env - DEBUG - Entering env context: <rasterio.env.Env object at 0x7f54201a0440>
2023-11-24 06:23:13,499 - rasterio.env - DEBUG - Got a copy of environment <rasterio._env.GDALEnv object at 0x7f54206153c0> options
2023-11-24 06:23:13,499 - rasterio.env - DEBUG - Entered env context: <rasterio.env.Env object at 0x7f54201a0440>
2023-11-24 06:23:13,500 - rasterio._base - DEBUG - Sharing flag: 0
2023-11-24 06:23:13,501 - rasterio._base - DEBUG - Nodata success: 1, Nodata value: nan
2023-11-24 06:23:13,501 - rasterio._base - DEBUG - Dataset <open DatasetReader name='https://radar.bmkg.go.id/raster/radarsatelit_202311240620.tif' mode='r'> is started.
2023-11-24 06:23:13,501 - rasterio.env - DEBUG - Exiting env context: <rasterio.env.Env object at 0x7f54201a0440>
2023-11-24 06:23:13,501 - rasterio.env - DEBUG - Cleared existing <rasterio._env.GDALEnv object at 0x7f54206153c0> options
2023-11-24 06:23:13,502 - rasterio._env - DEBUG - Stopped GDALEnv <rasterio._env.GDALEnv object at 0x7f54206153c0>.
2023-11-24 06:23:13,502 - rasterio.env - DEBUG - No GDAL environment exists
2023-11-24 06:23:13,502 - rasterio.env - DEBUG - New GDAL environment <rasterio._env.GDALEnv object at 0x7f54206153c0> created
2023-11-24 06:23:13,502 - rasterio._env - DEBUG - GDAL data found in package: path='/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/rasterio/gdal_data'.
2023-11-24 06:23:13,502 - rasterio._env - DEBUG - PROJ_LIB found in environment.
2023-11-24 06:23:13,503 - rasterio._env - DEBUG - Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x7f54206153c0>.
2023-11-24 06:23:13,503 - rasterio.env - DEBUG - Exited env context: <rasterio.env.Env object at 0x7f54201a0440>
2023-11-24 06:23:13,529 - rasterio._io - DEBUG - Output nodata value read from file: nan
2023-11-24 06:23:13,530 - rasterio._io - DEBUG - Output nodata values: [nan]
2023-11-24 06:23:13,530 - rasterio._io - DEBUG - all_valid: False
2023-11-24 06:23:13,530 - rasterio._io - DEBUG - mask_flags: ([<MaskFlags.nodata: 8>],)
2023-11-24 06:23:13,530 - rasterio._io - DEBUG - Jump straight to _read()
2023-11-24 06:23:13,530 - rasterio._io - DEBUG - Window: Window(col_off=0, row_off=0, width=10178, height=3732)
2023-11-24 06:23:13,531 - rasterio._io - DEBUG - IO window xoff=0.0 yoff=0.0 width=10178.0 height=3732.0
2023-11-24 06:23:14,434 - rasterio.env - DEBUG - Exiting env context: <rasterio.env.Env object at 0x7f5420e8c0b0>
2023-11-24 06:23:14,435 - rasterio.env - DEBUG - Cleared existing <rasterio._env.GDALEnv object at 0x7f54206153c0> options
2023-11-24 06:23:14,435 - rasterio._env - DEBUG - Stopped GDALEnv <rasterio._env.GDALEnv object at 0x7f54206153c0>.
2023-11-24 06:23:14,435 - rasterio.env - DEBUG - Exiting outermost env
2023-11-24 06:23:14,435 - rasterio.env - DEBUG - Exited env context: <rasterio.env.Env object at 0x7f5420e8c0b0>
2023-11-24 06:23:14,437 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): radar.bmkg.go.id:8060
2023-11-24 06:23:14,495 - urllib3.connectionpool - DEBUG - https://radar.bmkg.go.id:8060 "GET /getLatestLD?typeData=1 HTTP/1.1" 200 56095
2023-11-24 06:23:14,525 - root - INFO - Generating present weather using RADAR data
2023-11-24 06:23:17,834 - root - INFO - dask.bag<lambda, npartitions=20>
2023-11-24 06:23:18,463 - rasterio.env - DEBUG - Entering env context: <rasterio.env.Env object at 0x7f3000757050>
2023-11-24 06:23:18,464 - rasterio.env - DEBUG - Starting outermost env
2023-11-24 06:23:18,465 - rasterio.env - DEBUG - No GDAL environment exists
2023-11-24 06:23:18,465 - rasterio.env - DEBUG - New GDAL environment <rasterio._env.GDALEnv object at 0x7f3000757250> created
2023-11-24 06:23:18,470 - rasterio._filepath - DEBUG - Installing FilePath filesystem handler plugin...
2023-11-24 06:23:18,470 - rasterio._env - DEBUG - GDAL data found in package: path='/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/rasterio/gdal_data'.
2023-11-24 06:23:18,470 - rasterio._env - DEBUG - PROJ_LIB found in environment.
2023-11-24 06:23:18,470 - rasterio._env - DEBUG - Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x7f3000757250>.
2023-11-24 06:23:18,470 - rasterio.env - DEBUG - Entered env context: <rasterio.env.Env object at 0x7f3000757050>
2023-11-24 06:23:18,471 - rasterio._base - DEBUG - Sharing flag: 0
2023-11-24 06:23:18,487 - rasterio._base - DEBUG - Nodata success: 0, Nodata value: 0.000000
2023-11-24 06:23:18,487 - rasterio._base - DEBUG - Dataset <open DatasetReader name='/home/swx/present_weather/src/H09_B13_Indonesia_20231124.Z0610.cor.tiff' mode='r'> is started.
2023-11-24 06:23:18,488 - rasterio.env - DEBUG - Exiting env context: <rasterio.env.Env object at 0x7f3000757050>
2023-11-24 06:23:18,488 - rasterio.env - DEBUG - Cleared existing <rasterio._env.GDALEnv object at 0x7f3000757250> options
2023-11-24 06:23:18,488 - rasterio._env - DEBUG - Stopped GDALEnv <rasterio._env.GDALEnv object at 0x7f3000757250>.
2023-11-24 06:23:18,488 - rasterio.env - DEBUG - Exiting outermost env
2023-11-24 06:23:18,488 - rasterio.env - DEBUG - Exited env context: <rasterio.env.Env object at 0x7f3000757050>
2023-11-24 06:23:18,489 - rasterio.env - DEBUG - Entering env context: <rasterio.env.Env object at 0x7f30007822d0>
2023-11-24 06:23:18,489 - rasterio.env - DEBUG - Starting outermost env
2023-11-24 06:23:18,489 - rasterio.env - DEBUG - No GDAL environment exists
2023-11-24 06:23:18,489 - rasterio.env - DEBUG - New GDAL environment <rasterio._env.GDALEnv object at 0x7f3000781630> created
2023-11-24 06:23:18,490 - rasterio._env - DEBUG - GDAL data found in package: path='/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/rasterio/gdal_data'.
2023-11-24 06:23:18,490 - rasterio._env - DEBUG - PROJ_LIB found in environment.
2023-11-24 06:23:18,490 - rasterio._env - DEBUG - Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x7f3000781630>.
2023-11-24 06:23:18,490 - rasterio.env - DEBUG - Entered env context: <rasterio.env.Env object at 0x7f30007822d0>
2023-11-24 06:23:18,491 - rasterio._base - DEBUG - Sharing flag: 0
2023-11-24 06:23:18,491 - rasterio._base - DEBUG - Nodata success: 0, Nodata value: 0.000000
2023-11-24 06:23:18,492 - rasterio._base - DEBUG - Dataset <open DatasetReader name='/home/swx/present_weather/src/H09_B13_Indonesia_20231124.Z0610.cor.tiff' mode='r'> is started.
2023-11-24 06:23:18,492 - rasterio.env - DEBUG - Exiting env context: <rasterio.env.Env object at 0x7f30007822d0>
2023-11-24 06:23:18,492 - rasterio.env - DEBUG - Cleared existing <rasterio._env.GDALEnv object at 0x7f3000781630> options
2023-11-24 06:23:18,492 - rasterio._env - DEBUG - Stopped GDALEnv <rasterio._env.GDALEnv object at 0x7f3000781630>.
2023-11-24 06:23:18,492 - rasterio.env - DEBUG - Exiting outermost env
2023-11-24 06:23:18,492 - rasterio.env - DEBUG - Exited env context: <rasterio.env.Env object at 0x7f30007822d0>
2023-11-24 06:23:18,509 - root - INFO - Generating present weather using SATELITE data
2023-11-24 06:23:41,251 - mylogger - ERROR - Exception: 
NoneType: None
2023-11-24 06:23:41,419 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1769' coro=<Client._gather.<locals>.wait() done, defined at /home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py:2209> exception=AllExit()>
Traceback (most recent call last):
  File "/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py", line 2218, in wait
    raise AllExit()
distributed.client.AllExit
2023-11-24 06:23:41,448 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1778' coro=<Client._gather.<locals>.wait() done, defined at /home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py:2209> exception=AllExit()>
Traceback (most recent call last):
  File "/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py", line 2218, in wait
    raise AllExit()
distributed.client.AllExit
2023-11-24 06:23:41,459 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1780' coro=<Client._gather.<locals>.wait() done, defined at /home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py:2209> exception=AllExit()>
Traceback (most recent call last):
  File "/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py", line 2218, in wait
    raise AllExit()
distributed.client.AllExit
2023-11-24 06:23:41,480 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1766' coro=<Client._gather.<locals>.wait() done, defined at /home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py:2209> exception=AllExit()>
Traceback (most recent call last):
  File "/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py", line 2218, in wait
    raise AllExit()
distributed.client.AllExit
2023-11-24 06:23:41,481 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1783' coro=<Client._gather.<locals>.wait() done, defined at /home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py:2209> exception=AllExit()>
Traceback (most recent call last):
  File "/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py", line 2218, in wait
    raise AllExit()
distributed.client.AllExit
2023-11-24 06:23:41,483 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1782' coro=<Client._gather.<locals>.wait() done, defined at /home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py:2209> exception=AllExit()>
Traceback (most recent call last):
  File "/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py", line 2218, in wait
    raise AllExit()
distributed.client.AllExit
2023-11-24 06:23:41,485 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1767' coro=<Client._gather.<locals>.wait() done, defined at /home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py:2209> exception=AllExit()>
Traceback (most recent call last):
  File "/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py", line 2218, in wait
    raise AllExit()
distributed.client.AllExit
2023-11-24 06:23:41,490 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1781' coro=<Client._gather.<locals>.wait() done, defined at /home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py:2209> exception=AllExit()>
Traceback (most recent call last):
  File "/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py", line 2218, in wait
    raise AllExit()
distributed.client.AllExit
2023-11-24 06:23:41,501 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1775' coro=<Client._gather.<locals>.wait() done, defined at /home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py:2209> exception=AllExit()>
Traceback (most recent call last):
  File "/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py", line 2218, in wait
    raise AllExit()
distributed.client.AllExit
2023-11-24 06:23:41,506 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1773' coro=<Client._gather.<locals>.wait() done, defined at /home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py:2209> exception=AllExit()>
Traceback (most recent call last):
  File "/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py", line 2218, in wait
    raise AllExit()
distributed.client.AllExit
2023-11-24 06:23:41,508 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1784' coro=<Client._gather.<locals>.wait() done, defined at /home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py:2209> exception=AllExit()>
Traceback (most recent call last):
  File "/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py", line 2218, in wait
    raise AllExit()
distributed.client.AllExit
2023-11-24 06:23:41,510 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1776' coro=<Client._gather.<locals>.wait() done, defined at /home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py:2209> exception=AllExit()>
Traceback (most recent call last):
  File "/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py", line 2218, in wait
    raise AllExit()
distributed.client.AllExit
2023-11-24 06:23:41,512 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1779' coro=<Client._gather.<locals>.wait() done, defined at /home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py:2209> exception=AllExit()>
Traceback (most recent call last):
  File "/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py", line 2218, in wait
    raise AllExit()
distributed.client.AllExit
2023-11-24 06:23:41,515 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1768' coro=<Client._gather.<locals>.wait() done, defined at /home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py:2209> exception=AllExit()>
Traceback (most recent call last):
  File "/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py", line 2218, in wait
    raise AllExit()
distributed.client.AllExit
2023-11-24 06:23:41,516 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1765' coro=<Client._gather.<locals>.wait() done, defined at /home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py:2209> exception=AllExit()>
Traceback (most recent call last):
  File "/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py", line 2218, in wait
    raise AllExit()
distributed.client.AllExit
2023-11-24 06:23:41,521 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1770' coro=<Client._gather.<locals>.wait() done, defined at /home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py:2209> exception=AllExit()>
Traceback (most recent call last):
  File "/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py", line 2218, in wait
    raise AllExit()
distributed.client.AllExit
2023-11-24 06:23:41,523 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1774' coro=<Client._gather.<locals>.wait() done, defined at /home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py:2209> exception=AllExit()>
Traceback (most recent call last):
  File "/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py", line 2218, in wait
    raise AllExit()
distributed.client.AllExit
2023-11-24 06:23:41,525 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1772' coro=<Client._gather.<locals>.wait() done, defined at /home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py:2209> exception=AllExit()>
Traceback (most recent call last):
  File "/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py", line 2218, in wait
    raise AllExit()
distributed.client.AllExit
2023-11-24 06:23:41,527 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1777' coro=<Client._gather.<locals>.wait() done, defined at /home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py:2209> exception=AllExit()>
Traceback (most recent call last):
  File "/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py", line 2218, in wait
    raise AllExit()
distributed.client.AllExit
2023-11-24 06:23:41,529 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1771' coro=<Client._gather.<locals>.wait() done, defined at /home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py:2209> exception=AllExit()>
Traceback (most recent call last):
  File "/home/swx/miniconda3/envs/present_weather/lib/python3.12/site-packages/distributed/client.py", line 2218, in wait
    raise AllExit()
distributed.client.AllExit
2023-11-24 06:24:42,522 - root - INFO - Total elapsed time: 0:01:39.173811
